services:
  - type: web
    name: rag-flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rag:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false 